//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocketAdvisor.Requests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PocketAdvisor.Requests.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting balance must not be negative.
        /// </summary>
        internal static string AccountBalanceNegative {
            get {
                return ResourceManager.GetString("AccountBalanceNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting balance is required.
        /// </summary>
        internal static string AccountBalanceRequired {
            get {
                return ResourceManager.GetString("AccountBalanceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currency code is invalid.
        /// </summary>
        internal static string AccountCurrencyCodeInvalid {
            get {
                return ResourceManager.GetString("AccountCurrencyCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currency code is required.
        /// </summary>
        internal static string AccountCurrencyCodeRequired {
            get {
                return ResourceManager.GetString("AccountCurrencyCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account name is required.
        /// </summary>
        internal static string AccountNameRequired {
            get {
                return ResourceManager.GetString("AccountNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account name must not exceed 100 characters.
        /// </summary>
        internal static string AccountNameTooLong {
            get {
                return ResourceManager.GetString("AccountNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category name is required.
        /// </summary>
        internal static string CategoryNameRequired {
            get {
                return ResourceManager.GetString("CategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category name must not exceed 100 characters.
        /// </summary>
        internal static string CategoryNameTooLong {
            get {
                return ResourceManager.GetString("CategoryNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password confirmation must match the password.
        /// </summary>
        internal static string ConfirmPasswordMismatch {
            get {
                return ResourceManager.GetString("ConfirmPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password confirmation is required.
        /// </summary>
        internal static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password confirmation must not exceed 100 characters.
        /// </summary>
        internal static string ConfirmPasswordTooLong {
            get {
                return ResourceManager.GetString("ConfirmPasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password confirmation must be at least 8 characters and include uppercase, lowercase, digit, and special character.
        /// </summary>
        internal static string ConfirmPasswordTooWeak {
            get {
                return ResourceManager.GetString("ConfirmPasswordTooWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address format is invalid.
        /// </summary>
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is required.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address must not exceed 100 characters.
        /// </summary>
        internal static string EmailTooLong {
            get {
                return ResourceManager.GetString("EmailTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email verification token is required.
        /// </summary>
        internal static string EmailVerificationTokenRequired {
            get {
                return ResourceManager.GetString("EmailVerificationTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email verification token must not exceed 44 characters.
        /// </summary>
        internal static string EmailVerificationTokenTooLong {
            get {
                return ResourceManager.GetString("EmailVerificationTokenTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email verification token must be at least 44 characters.
        /// </summary>
        internal static string EmailVerificationTokenTooShort {
            get {
                return ResourceManager.GetString("EmailVerificationTokenTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item name is required.
        /// </summary>
        internal static string ItemNameRequired {
            get {
                return ResourceManager.GetString("ItemNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item name must not exceed 100 characters.
        /// </summary>
        internal static string ItemNameTooLong {
            get {
                return ResourceManager.GetString("ItemNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit category is invalid.
        /// </summary>
        internal static string ItemUnitCategoryInvalid {
            get {
                return ResourceManager.GetString("ItemUnitCategoryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unit category is required.
        /// </summary>
        internal static string ItemUnitCategoryRequired {
            get {
                return ResourceManager.GetString("ItemUnitCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is required.
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password reset token is required.
        /// </summary>
        internal static string PasswordResetTokenRequired {
            get {
                return ResourceManager.GetString("PasswordResetTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password reset token must not exceed 44 characters.
        /// </summary>
        internal static string PasswordResetTokenTooLong {
            get {
                return ResourceManager.GetString("PasswordResetTokenTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password reset token must be at least 44 characters.
        /// </summary>
        internal static string PasswordResetTokenTooShort {
            get {
                return ResourceManager.GetString("PasswordResetTokenTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must not exceed 100 characters.
        /// </summary>
        internal static string PasswordTooLong {
            get {
                return ResourceManager.GetString("PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must be at least 8 characters and include uppercase, lowercase, digit, and special character.
        /// </summary>
        internal static string PasswordTooWeak {
            get {
                return ResourceManager.GetString("PasswordTooWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token is required.
        /// </summary>
        internal static string RefreshTokenRequired {
            get {
                return ResourceManager.GetString("RefreshTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token must not exceed 44 characters.
        /// </summary>
        internal static string RefreshTokenTooLong {
            get {
                return ResourceManager.GetString("RefreshTokenTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token must be at least 44 characters.
        /// </summary>
        internal static string RefreshTokenTooShort {
            get {
                return ResourceManager.GetString("RefreshTokenTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source and destination accounts must be different.
        /// </summary>
        internal static string TransactionAccountsSame {
            get {
                return ResourceManager.GetString("TransactionAccountsSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category is required.
        /// </summary>
        internal static string TransactionCategoryIdRequired {
            get {
                return ResourceManager.GetString("TransactionCategoryIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transaction must have either a source account, a destination account, or both.
        /// </summary>
        internal static string TransactionEitherAccountRequired {
            get {
                return ResourceManager.GetString("TransactionEitherAccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item amount must be greater than zero.
        /// </summary>
        internal static string TransactionItemAmountNegative {
            get {
                return ResourceManager.GetString("TransactionItemAmountNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item amount is required.
        /// </summary>
        internal static string TransactionItemAmountRequired {
            get {
                return ResourceManager.GetString("TransactionItemAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is required.
        /// </summary>
        internal static string TransactionItemIdRequired {
            get {
                return ResourceManager.GetString("TransactionItemIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one transaction item is required.
        /// </summary>
        internal static string TransactionItemsRequired {
            get {
                return ResourceManager.GetString("TransactionItemsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total price must not be negative.
        /// </summary>
        internal static string TransactionItemTotalPriceNegative {
            get {
                return ResourceManager.GetString("TransactionItemTotalPriceNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total price is required.
        /// </summary>
        internal static string TransactionItemTotalPriceRequired {
            get {
                return ResourceManager.GetString("TransactionItemTotalPriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount unit is invalid.
        /// </summary>
        internal static string TransactionItemUnitInvalid {
            get {
                return ResourceManager.GetString("TransactionItemUnitInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount unit is required.
        /// </summary>
        internal static string TransactionItemUnitRequired {
            get {
                return ResourceManager.GetString("TransactionItemUnitRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The occurrence date must not be in the future.
        /// </summary>
        internal static string TransactionOccurredAtFuture {
            get {
                return ResourceManager.GetString("TransactionOccurredAtFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The occurrence date is required.
        /// </summary>
        internal static string TransactionOccurredAtRequired {
            get {
                return ResourceManager.GetString("TransactionOccurredAtRequired", resourceCulture);
            }
        }
    }
}
