<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PocketAdvisor.Repositories\PocketAdvisor.Repositories.csproj" />
    <ProjectReference Include="..\PocketAdvisor.Requests\PocketAdvisor.Requests.csproj" />
    <ProjectReference Include="..\PocketAdvisor.Responses\PocketAdvisor.Responses.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>

</Project>
