<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PocketAdvisor.Repositories\PocketAdvisor.Repositories.csproj" />
    <ProjectReference Include="..\PocketAdvisor.Requests\PocketAdvisor.Requests.csproj" />
    <ProjectReference Include="..\PocketAdvisor.Responses\PocketAdvisor.Responses.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\ValidationMessages.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ValidationMessages.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\ValidationMessages.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ValidationMessages.resx</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
