<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Resend" />
    <PackageReference Include="SecureStore" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PocketAdvisor.Services\PocketAdvisor.Services.csproj" />
  </ItemGroup>

</Project>
